version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn test
  codecov-upload:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: target/codecov
      - codecov/upload
  checkstyle:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: target/checkstyle
      - run: mvn post-site
  build-docs:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn javadoc:javadoc
      - persist_to_workspace:
          root: target/site
          paths: apidocs
  deploy-docs:
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - attach_workspace:
          at: target/site
      - run :
            name: Installing dependencies
            command: |
              npm install need sudo
              git config user.email "gerome12327@gmail.com"
              git config user.name "Isio19"
              sudo npm install -g gh-pages --save-dev
      - add_ssh_keys:
          fingerprints: 
              - SHA256:yH48Xn1/r1Kx7GgzPLZAfLiXulYFDQ8ECM+sE5XlVAw
      - run : gh-pages --dist target/site/apidocs

orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  test:
    jobs:
      - test:
        filters:
          branches:
            only: master
  upload-to-codecov:
    jobs:
      - codecov-upload
  checkstyle:
    jobs:
      - checkstyle
  make-docs:
    jobs:
      - build-docs
      - deploy-docs