version: 2.1

jobs:
  test: 
    docker:
      - image: cimg/openjdk:21.0.2-node
    steps:
      - checkout
      - run: mvn test 

workflows:
  test:
    jobs:
      - test:
        filters:
          branches:
            only: master
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Isio-19/techniques-de-test
